name: LP Logger

on:
  schedule:
    - cron: "0 * * * *"   # 毎時実行
  workflow_dispatch:       # 手動実行も可能

jobs:
  run-logger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install web3

      - name: Run logger
        run: python lp_logger.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add lp_history.csv
          git commit -m "update LP history" || echo "No changes"
          git push
