name: LP Logger (daily JST)

on:
  schedule:
    # GitHub Actions は UTC で動きます。00:00 JST = 15:00 UTC 前日
    - cron: "0 15 * * *"   # 毎日 00:00 JST に1回実行
  workflow_dispatch:        # 手動実行も可能

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests web3 pandas matplotlib

      - name: Run script
        run: |
          python lp_logger.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lp_history.csv lp_value_*.png
          git commit -m "Update LP history & graph (JST daily) [skip ci]" || echo "No changes to commit"
          git push
